<a href="https://colab.research.google.com/github/FriendzoneGuardian/Academics/blob/main/Final_Examination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Calling of Libraries**

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
plt.style.use('dark_background')
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.colors import ListedColormap
from scipy.stats import norm, boxcox
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from collections import Counter
from scipy import stats
from tqdm import tqdm_notebook

**Generating of Dataset**

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datafiles/WineQT.csv')

**Displaying and checking of generated Dataset ( Pre Processing )**

In [ ]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4

**Checking any Null Values**

In [ ]:
dataset.isnull().values.any()

False

In [ ]:
dataset.dropna(inplace =True)

In [ ]:
dataset[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide", "total sulfur dioxide", "pH", "alcohol"]].fillna(method='ffill')

fixed acidity  volatile acidity  citric acid  residual sugar  \
0               7.4             0.700         0.00             1.9   
1               7.8             0.880         0.00             2.6   
2               7.8             0.760         0.04             2.3   
3              11.2             0.280         0.56             1.9   
4               7.4             0.700         0.00             1.9   
...             ...               ...          ...             ...   
1138            6.3             0.510         0.13             2.3   
1139            6.8             0.620         0.08             1.9   
1140            6.2             0.600         0.08             2.0   
1141            5.9             0.550         0.10             2.2   
1142            5.9             0.645         0.12             2.0   

      free sulfur dioxide  total sulfur dioxide    pH  alcohol  
0                    11.0                  34.0  3.51      9.4  
1                    25.0                  67.0  3.20      9.8  
2                    15.0                  54.0  3.26      9.8  
3                    17.0                  60.0  3.16      9.8  
4                    11.0                  34.0  3.51      9.4  
...                   ...                   ...   ...      ...  
1138                 29.0                  40.0  3.42     11.0  
1139                 28.0                  38.0  3.42      9.5  
1140                 32.0                  44.0  3.45     10.5  
1141                 39.0                  51.0  3.52     11.2  
1142                 32.0                  44.0  3.57     10.2  

[1143 rows x 8 columns]

In [ ]:
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

**Filling out Missing Values**

In [ ]:
dataset.fillna(dataset.mean()).isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

**Checking if dataset is balanced then apply oversampling and undersampling in order to balance Dataset**

In [ ]:
dataset.shape

(1143, 13)

In [ ]:
print(sorted(Counter(dataset['quality']).items()))

[(3, 6), (4, 33), (5, 483), (6, 462), (7, 143), (8, 16)]


In [ ]:
water_potable = dataset[dataset['quality']==1]
water_nonpotable = dataset[dataset['quality']==0]

In [ ]:
X = dataset
Y= dataset['quality']

In [ ]:
X.drop('Id', axis =1, inplace=True)
X.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
X.drop('quality',axis=1,inplace=True)

In [ ]:
!pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from imblearn import under_sampling, over_sampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X,Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)

[(3, 483), (4, 483), (5, 483), (6, 483), (7, 483), (8, 483)] (2898,)


In [ ]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = rus.fit_resample(X,Y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)

[(3, 6), (4, 6), (5, 6), (6, 6), (7, 6), (8, 6)] (36,)


In [ ]:
from sklearn.preprocessing import StandardScaler 

In [ ]:
X = X_resampled
Y = y_resampled

In [ ]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            11.6             0.580         0.66             2.2      0.074   
1            10.4             0.610         0.49             2.1      0.200   
2             7.6             1.580         0.00             2.1      0.137   
3             7.3             0.980         0.05             2.1      0.061   
4             7.1             0.875         0.05             5.7      0.082   
5             6.7             0.760         0.02             1.8      0.078   
6            10.1             0.935         0.22             3.4      0.105   
7             7.5             0.685         0.07             2.5      0.058   
8             8.3             0.625         0.20             1.5      0.080   
9             6.3             1.020         0.00             2.0      0.083   
10            6.7             1.040         0.08             2.3      0.067   
11            6.5             0.670         0.00             4.3      0.057   
12            8.4             0.590         0.29             2.6      0.109   
13            7.1             0.520         0.03             2.6      0.076   
14            9.9             0.570         0.25             2.0      0.104   
15            7.1             0.560         0.14             1.6      0.078   
16            9.0             0.690         0.00             2.4      0.088   
17            6.3             0.390         0.08             1.7      0.066   
18            8.4             0.340         0.42             2.1      0.072   
19            7.8             0.340         0.37             2.0      0.082   
20           10.2             0.290         0.65             2.4      0.075   
21            6.7             0.620         0.21             1.9      0.079   
22           13.7             0.415         0.68             2.9      0.085   
23            5.2             0.340         0.00             1.8      0.050   
24           12.8             0.615         0.66             5.8      0.083   
25            6.4             0.570         0.12             2.3      0.120   
26            4.9             0.420         0.00             2.1      0.048   
27           10.4             0.330         0.63             2.8      0.084   
28           10.5             0.510         0.64             2.4      0.107   
29            7.9             0.340         0.36             1.9      0.065   
30            5.0             0.420         0.24             2.0      0.060   
31            8.6             0.420         0.39             1.8      0.068   
32            7.9             0.350         0.46             3.6      0.078   
33           12.6             0.310         0.72             2.2      0.072   
34            7.2             0.380         0.31             2.0      0.056   
35            9.1             0.400         0.50             1.8      0.071   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  10.0                  47.0  1.00080  3.25       0.57   
1                   5.0                  16.0  0.99940  3.16       0.63   
2                   5.0                   9.0  0.99476  3.50       0.40   
3                  20.0                  49.0  0.99705  3.31       0.55   
4                   3.0                  14.0  0.99808  3.40       0.52   
5                   6.0                  12.0  0.99600  3.55       0.63   
6                  11.0                  86.0  1.00100  3.43       0.64   
7                   5.0                   9.0  0.99632  3.38       0.55   
8                  27.0                 119.0  0.99720  3.16       1.12   
9                  17.0                  24.0  0.99437  3.59       0.55   
10                 19.0                  32.0  0.99648  3.52       0.57   
11                 11.0                  20.0  0.99488  3.45       0.56   
12                 31.0                 119.0  0.99801  3.15       0.50   
13                 21.0       

In [ ]:
Y

0     3
1     3
2     3
3     3
4     3
5     3
6     4
7     4
8     4
9     4
10    4
11    4
12    5
13    5
14    5
15    5
16    5
17    5
18    6
19    6
20    6
21    6
22    6
23    6
24    7
25    7
26    7
27    7
28    7
29    7
30    8
31    8
32    8
33    8
34    8
35    8
Name: quality, dtype: int64

In [ ]:
X.shape, Y.shape

((36, 11), (36,))

**Applying Feature Selection**

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from numpy import set_printoptions

In [ ]:
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)

In [ ]:
set_printoptions(precision=3)
print(fit.scores_)

[0.244 8.617 2.829 0.565 1.48  1.18  1.704 0.53  0.397 1.792 4.03 ]


In [ ]:
features = fit.transform(X)
# Summarize selected features
print(features[0:5,:])

[[ 0.58   0.66   0.57   9.   ]
 [ 0.61   0.49   0.63   8.4  ]
 [ 1.58   0.     0.4   10.9  ]
 [ 0.98   0.05   0.55   9.7  ]
 [ 0.875  0.05   0.52  10.2  ]]


In [ ]:
fit.get_feature_names_out()

array(['volatile acidity', 'citric acid', 'sulphates', 'alcohol'],
      dtype=object)

In [ ]:
print(features)

[[ 0.58   0.66   0.57   9.   ]
 [ 0.61   0.49   0.63   8.4  ]
 [ 1.58   0.     0.4   10.9  ]
 [ 0.98   0.05   0.55   9.7  ]
 [ 0.875  0.05   0.52  10.2  ]
 [ 0.76   0.02   0.63   9.95 ]
 [ 0.935  0.22   0.64  11.3  ]
 [ 0.685  0.07   0.55  10.9  ]
 [ 0.625  0.2    1.12   9.1  ]
 [ 1.02   0.     0.55  11.2  ]
 [ 1.04   0.08   0.57  11.   ]
 [ 0.67   0.     0.56  11.8  ]
 [ 0.59   0.29   0.5    9.1  ]
 [ 0.52   0.03   0.6    9.8  ]
 [ 0.57   0.25   0.9   10.1  ]
 [ 0.56   0.14   0.62   9.3  ]
 [ 0.69   0.     0.6    9.3  ]
 [ 0.39   0.08   0.58   9.4  ]
 [ 0.34   0.42   0.78  12.4  ]
 [ 0.34   0.37   0.59   9.4  ]
 [ 0.29   0.65   0.63  11.8  ]
 [ 0.62   0.21   0.58   9.3  ]
 [ 0.415  0.68   0.8   10.   ]
 [ 0.34   0.     0.79  14.   ]
 [ 0.615  0.66   0.73  10.   ]
 [ 0.57   0.12   0.71  11.3  ]
 [ 0.42   0.     0.74  14.   ]
 [ 0.33   0.63   0.74  11.2  ]
 [ 0.51   0.64   0.66  11.8  ]
 [ 0.34   0.36   0.54  11.2  ]
 [ 0.42   0.24   0.74  14.   ]
 [ 0.42   0.39   0.69  11.7  ]
 [ 0.35 

In [ ]:
X = features

In [ ]:
X, Y

(array([[ 0.58 ,  0.66 ,  0.57 ,  9.   ],
        [ 0.61 ,  0.49 ,  0.63 ,  8.4  ],
        [ 1.58 ,  0.   ,  0.4  , 10.9  ],
        [ 0.98 ,  0.05 ,  0.55 ,  9.7  ],
        [ 0.875,  0.05 ,  0.52 , 10.2  ],
        [ 0.76 ,  0.02 ,  0.63 ,  9.95 ],
        [ 0.935,  0.22 ,  0.64 , 11.3  ],
        [ 0.685,  0.07 ,  0.55 , 10.9  ],
        [ 0.625,  0.2  ,  1.12 ,  9.1  ],
        [ 1.02 ,  0.   ,  0.55 , 11.2  ],
        [ 1.04 ,  0.08 ,  0.57 , 11.   ],
        [ 0.67 ,  0.   ,  0.56 , 11.8  ],
        [ 0.59 ,  0.29 ,  0.5  ,  9.1  ],
        [ 0.52 ,  0.03 ,  0.6  ,  9.8  ],
        [ 0.57 ,  0.25 ,  0.9  , 10.1  ],
        [ 0.56 ,  0.14 ,  0.62 ,  9.3  ],
        [ 0.69 ,  0.   ,  0.6  ,  9.3  ],
        [ 0.39 ,  0.08 ,  0.58 ,  9.4  ],
        [ 0.34 ,  0.42 ,  0.78 , 12.4  ],
        [ 0.34 ,  0.37 ,  0.59 ,  9.4  ],
        [ 0.29 ,  0.65 ,  0.63 , 11.8  ],
        [ 0.62 ,  0.21 ,  0.58 ,  9.3  ],
        [ 0.415,  0.68 ,  0.8  , 10.   ],
        [ 0.34 ,  0.   ,  0.79 , 1

In [ ]:
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [ ]:
standardized_data = scaler.transform(X)

In [ ]:
X.shape

(36, 4)

In [ ]:
Y.shape

(36,)

In [ ]:
X = standardized_data

In [ ]:
print(X)

[[-0.022  1.585 -0.711 -1.235]
 [ 0.09   0.881 -0.262 -1.646]
 [ 3.72  -1.15  -1.984  0.066]
 [ 1.475 -0.943 -0.861 -0.756]
 [ 1.082 -0.943 -1.085 -0.414]
 [ 0.652 -1.067 -0.262 -0.585]
 [ 1.307 -0.238 -0.187  0.34 ]
 [ 0.371 -0.86  -0.861  0.066]
 [ 0.147 -0.321  3.406 -1.167]
 [ 1.625 -1.15  -0.861  0.271]
 [ 1.7   -0.818 -0.711  0.134]
 [ 0.315 -1.15  -0.786  0.682]
 [ 0.016  0.052 -1.235 -1.167]
 [-0.246 -1.026 -0.487 -0.688]
 [-0.059 -0.114  1.759 -0.482]
 [-0.097 -0.57  -0.337 -1.03 ]
 [ 0.39  -1.15  -0.487 -1.03 ]
 [-0.733 -0.818 -0.636 -0.961]
 [-0.92   0.591  0.861  1.093]
 [-0.92   0.383 -0.561 -0.961]
 [-1.107  1.544 -0.262  0.682]
 [ 0.128 -0.28  -0.636 -1.03 ]
 [-0.639  1.668  1.011 -0.551]
 [-0.92  -1.15   0.936  2.188]
 [ 0.109  1.585  0.487 -0.551]
 [-0.059 -0.653  0.337  0.34 ]
 [-0.621 -1.15   0.561  2.188]
 [-0.957  1.461  0.561  0.271]
 [-0.284  1.502 -0.037  0.682]
 [-0.92   0.342 -0.936  0.271]
 [-0.621 -0.155  0.561  2.188]
 [-0.621  0.466  0.187  0.613]
 [-0.882

In [ ]:
print(Y)

0     3
1     3
2     3
3     3
4     3
5     3
6     4
7     4
8     4
9     4
10    4
11    4
12    5
13    5
14    5
15    5
16    5
17    5
18    6
19    6
20    6
21    6
22    6
23    6
24    7
25    7
26    7
27    7
28    7
29    7
30    8
31    8
32    8
33    8
34    8
35    8
Name: quality, dtype: int64


**Applying Data Mining**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn import svm

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, stratify = Y, random_state = 2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(36, 4) (25, 4) (11, 4)


In [ ]:
#classifier = svm.SVC(kernel='sigmoid')
classifier = make_pipeline(StandardScaler(), LogisticRegression())

In [ ]:
classifier.fit(X_train,Y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [ ]:
#Accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
#Accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score of the training data : ', training_data_accuracy)
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the training data :  0.72
Accuracy score of the test data :  0.2727272727272727


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(Y_test,X_test_prediction)

array([[0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0]])

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/datafiles

/content/drive/MyDrive/Colab Notebooks/datafiles


In [ ]:
%%writefile waterqualitywithfSandOS.py
import streamlit as st
st.write('waterqualitywithfSandOS')
st.write('waterqualitywithfSandOS')

Writing waterqualitywithfSandOS.py


In [ ]:
input_data = ([[6.504876222,159.1821388,13403.08639,6.958284224]] )

#Input_data = (20418.88993, 7.214895724, 325.2288808, 16.80039961)

#Changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#Reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#Standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The wine is low quality')
else:
  print('The wine is high quality')

[[ 2.215e+01  6.585e+02  1.003e+05 -2.633e+00]]
[8]
The wine is high quality


In [ ]:
import pickle

In [ ]:
filename = 'waterquality_trainedModel.sav'
pickle.dump(classifier,open(filename,'wb'))

In [ ]:
loaded_model = pickle.load(open('waterquality_trainedModel.sav','rb'))

In [ ]:
input_data = ([[6.504876222,159.1821388,13403.08639,6.958284224]] )

#input_data = (20418.88993, 7.214895724, 325.2288808, 16.80039961)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The wine is low quality')
else:
  print('The wine is high quality')

[[ 2.215e+01  6.585e+02  1.003e+05 -2.633e+00]]
[8]
The wine is high quality
